### ISSUE TITLE
Clarify the license

### ISSUE THREAD

**Issue by link2xt** [Peltoche/ical-rs#38]
The commit named [Change the License for MIT](https://github.com/Peltoche/ical-rs/commit/f45fc1f6d04bb7b63fa88bd8ee029b84abe9d82f) actually uploads Apache 2.0. Not sure if this is what you wanted to do, or just uploaded the wrong file.

It is common for Rust projects to specify `license = "MIT OR Apache-2.0"` as discussed here: https://rust-lang.github.io/api-guidelines/necessities.html
Probably this is what you wanted to do.

**Comment by Peltoche** [comment]
Hello @link2xt,

I don't know why I have specified MIT inside the message commit, I always expected to have a MIT license so everything is good. :+1: 

I will make a minor change inside the LICENSE file in order to change the message seen in github in order to avoid confusion.

Thanks for the report
